spring:
  datasource:
    dynamic:
      primary: mysql #设置默认的数据源或者数据源组,默认值即为master
      strict: false #严格匹配数据源,默认false. true未匹配到指定数据源时抛异常,false使用默认数据源
      datasource:
        mysql:
          type: com.alibaba.druid.pool.DruidDataSource
          driverClassName: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://101.37.117.226:3306/xjd_039_zyc_service?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&useSSL=false&serverTimezone=GMT%2B8
          username: root
          password: 123456
          druid:
            validationQuery: SELECT 1 FROM DUAL
            testWhileIdle: true
            testOnBorrow: false
            testOnReturn: false
          #druid配置
          #配置初始化大小/最小/最大
          initialSize: 5
          minIdle: 5
          maxActive: 20
          #获取连接等待超时时间
          maxWait: 60000
          #间隔多久进行一次检测，检测需要关闭的空闲连接
          timeBetweenEvictionRunsMillis: 60000
          #一个连接在池中最小生存的时间
          minEvictableIdleTimeMillis: 300000
          validationQuery: SELECT 1 FROM DUAL
          testWhileIdle: true
          testOnBorrow: false
          testOnReturn: false
          maxPoolPreparedStatementPerConnectionSize: 20
          # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
          connectionProperties:
            druid:
              stat:
                mergeSql: true
                slowSqlMillis: 5000

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# 去掉es和redis的健康监听
management:
  health:
    elasticsearch:
      enabled: false
    redis:
      enabled: false


ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000